### ISSUE TITLE
planning district tiles when there is no data

### ISSUE THREAD

**Issue by MeaganLP** [CityOfPhiladelphia/community-health-explorer#50] opened 2016-07-11 13:59 UTC
I'm not sure where we've tried to go on this in the past... but we like it the way it looks on our computers currently - where a tile appears if there is no data, but the green data portion is missing. Ideally, there would be a dash ('-') there, but it's not necessary.

**Comment by laurenancona** [comment] 2016-07-11 15:25
### Testing

| Machine | OS | Browser | Version | Network | Issue |
| --- | --- | --- | --- | --- | --- |
| Meagan | Win 7  Pro | Firefox | 47.0.1 | Health | Planning: No padding bottom Built Env, SHS doesn't appear |
| Meagan | Win 7 Pro | IE | 11.0.9600.18347 | Health | Planning: No padding bottom Built Env, SHS doesn't appear |

**Comment by laurenancona** [comment] 2016-07-11 18:45
Closing because this is duplicate of #49

**Closed as completed by laurenancona** 2016-07-11 18:45 UTC
Labels: duplicate, launch
