### ISSUE TITLE
Planning districts - SHS exposure not showing up

### ISSUE THREAD

**Issue by MeaganLP** [CityOfPhiladelphia/community-health-explorer#49] opened 2016-07-08 14:56 UTC
@laurenancona SHS exposure is not showing up for any planning district; Maybe this is an easy bug to fix?

**Comment by Kistine** [comment] 2016-07-08 14:59
@MeaganLP - not sure if you saw my slack but  I just double-checked the data and the regions for which the second-hand smoke or excessive drinking cards don't appear is because the data field is empty. are you not seeing SHS AT ALL for ANY district?

**Comment by laurenancona** [comment] 2016-07-08 15:00
![screen shot 2016-07-08 at 11 00 20 am](https://cloud.githubusercontent.com/assets/2152151/16691596/388fe912-44fb-11e6-8b5e-331ea16940cb.png)

Note: #50 is a duplicate of this issue

**Comment by laurenancona** [comment] 2016-07-08 18:35
@MeaganLP @AmoryH Have tested this in Firefox 47 on Windows 7-10, Mac back to Yosemite. I'll work through the rest of the common OS browser combos, but please let me know if you encounter any other specific combos and I'll try to reproduce.

**Comment by laurenancona** [comment] 2016-07-11 17:59
Testing

| Machine | Network | OS | Browser | Version | Notes |
| --- | --- | --- | --- | --- | --- |
| Ancona | LTE | OSX 10.10 | Chrome | current | OK |
| Ancona | LTE | OSX 10.10 | Safari | current | OK |
| Browserstack | BS | Win 7-10 | Firefox | 47.0.1 | OK |
| Hannah | Health LAN | Win 7 | Chrome | current | OK |

**Comment by laurenancona** [comment] 2016-07-11 18:05
@AmoryH @MeaganLP @Kistine @timwis 
Ok. We've isolated the issue to when you use the dropdown to change planning district - it does not add/remove the class to hide/show indicators with `null`, `0`, or `0%` values, whereas when you use the map to select, this works correctly.

**To reproduce:** after page loads, scroll or jump to [`Tobacco & Alcohol`](http://cityofphiladelphia.github.io/community-health-explorer/planning-districts/#tobacco-and-alcohol) Category, try changing the planning district via the map, and then try same via the dropdown. E.g.: `Central` (loaded by default) has no data for `Secondhand Smoke exposure`, so there should be 3 indicators, and when you select `Lower North` (directly above `Central`) a 4th indicator (`Secondhand Smoke`) should appear.

**Comment by Kistine** [comment] 2016-07-11 19:41
bizarro!

**Comment by laurenancona** [comment] 2016-07-14 15:10
Waiting for results of exec review before making any more changes on this.

**Comment by laurenancona** [comment] 2016-08-03 16:57
closed in fd16a59

**Closed as completed by laurenancona** 2016-08-03 16:57 UTC
Labels: bug, help wanted, launch
